server:
  port: 18891


spring:
  profiles:
    active: dev
  application:
    name: molly-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    locale: zh_CN


  jpa:
    hibernate:
      ddl-auto: none


  liquibase:
    enabled: true
    change-log: ${multi.tenant.master-change-log}


# 多租户配置
multi:
  tenant:
    create-table: true
    db-style: schema
    master-change-log: classpath:db/changelog-master.xml
    other-change-log: classpath:db/changelog-other.xml
    prefix: molly_
    default-tenant-id: master


info:
  app:
    name: ${customize.swagger.title}
    description: ${customize.swagger.description}
    version: ${customize.swagger.version}


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
