spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/molly_master?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10               #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      minimum-idle: 5                     #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      connection-test-query: SELECT 1     #连接测试查询


  data:
    redis:
      database: 0
      timeout: 5000
      sentinel:
        master: molly_master
        nodes:
          - 192.168.0.101:26379
          - 192.168.0.102:26379
          - 192.168.0.103:26379
      lettuce:
        pool:
          max-idle: 8         # 连接池中的最大空闲连接
          min-idle: 3         # 连接池中的最小空闲连接
          max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
          max-wait: 500       # 连接池最大阻塞等待时间（使用负值表示没有限制）
  cache:
    type: redis
    redis:
      use-key-prefix: true
      time-to-live: 60s
