spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/molly_master?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource


  redis:
    database: 0
    port: 6379
    #host: 127.0.0.1
    host: 192.168.0.189
    password: mht123
    timeout: 5000
    lettuce:
      pool:
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 3         # 连接池中的最小空闲连接
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 500       # 连接池最大阻塞等待时间（使用负值表示没有限制）
  cache:
    type: redis
    redis:
      use-key-prefix: true
      time-to-live: 180s


# mybatis-plus 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
