server:
  port: 18891


spring:
  profiles:
    active: dev
  application:
    name: molly-multi-tenant
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    locale: zh_CN
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


  liquibase:
    enabled: true
    change-log: ${multi.tenant.master-change-log}


# mybatis-plus 自动配置
mybatis-plus:
  type-aliases-package: com.xaaef.molly.*.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


# 多租户配置
multi:
  tenant:
    create-table: true
    db-style: schema
    master-change-log: classpath:db/changelog-master.xml
    other-change-log: classpath:db/changelog-other.xml
    prefix: molly_
    default-tenant-id: master


info:
  app:
    name: ${spring.application.name}
    description: molly mybatis-plus multi tenant sass platform
    version: 1.0.1


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
